### ISSUE TITLE
Security issue on lodash and diff

### ISSUE THREAD

**Issue by hthetiot** [hthetiot/node-snowball#12]
More information :
- https://github.com/hthetiot/node-snowball/network/alerts

**Comment by rm-hull** [comment]
Hey @hthetiot 

I get a 404 on that URL.(presumably only repo admin can see that page)

Has this been fixed since I committed https://github.com/hthetiot/node-snowball/commit/044e3b6cb85e3e6c54374c1464df714ba9709fa3 ?

**Comment by hthetiot** [comment]
@rm-hull Sorry I still see the alert.
I dont find a wayt to add you as admin on a single repository.
Let me know if we should do an organisation to solve that.

**Comment by hthetiot** [comment]
<img width="749" alt="Screen Shot 2019-10-24 at 2 41 15 PM" src="https://user-images.githubusercontent.com/8635/67486468-60a77980-f66c-11e9-936a-4637195e08a4.png">
![Uploading Screen Shot 2019-10-24 at 2.41.24 PM.png…]()

**Comment by rm-hull** [comment]
```

**Comment by hthetiot** [comment]
@rm-hull I'm fine with that, I dont want to give you too much work :)
what about `npm audit --prod`

**Comment by rm-hull** [comment]
I've pushed a change to use jest now instead - basically swapping a whole bunch of one dependencies for another ... hopefully this will have resolved the security fix and I guess looking forward, jest has got better long term prospects than nodetest.

**Comment by rm-hull** [comment]
closing - please reopen if the security alert is still present

**Comment by hthetiot** [comment]
Thank you @rm-hull  there is 2 new one LOL.

<img width="765" alt="Screen Shot 2020-05-04 at 7 09 06 PM" src="https://user-images.githubusercontent.com/8635/80993085-c2764680-8e3a-11ea-9f61-96c03360309e.png">
<img width="776" alt="Screen Shot 2020-05-04 at 7 09 10 PM" src="https://user-images.githubusercontent.com/8635/80993092-c4d8a080-8e3a-11ea-81f1-15c9803fdc0d.png">

<img width="770" alt="Screen Shot 2020-05-04 at 7 07 50 PM" src="https://user-images.githubusercontent.com/8635/80993028-abcfef80-8e3a-11ea-91b1-c83eef7d46ba.png">

**Comment by hthetiot** [comment]
It's not even us that sub depenencies.

**Comment by hthetiot** [comment]
let see if that help https://github.com/hthetiot/node-snowball/pull/16
